/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AprovarTokenRouteImport } from './routes/aprovar.$token'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedCampanhasCampanhaIdRouteImport } from './routes/_authenticated/campanhas.$campanhaId'
import { Route as AuthenticatedPecasIndexRouteImport } from './routes/_authenticated/pecas.index'
import { Route as AuthenticatedPecasPecaIdRouteImport } from './routes/_authenticated/pecas.$pecaId'
import { Route as ApiPublicNotificacaoEmailRouteImport } from './routes/api/public/notificacao-email'
import { Route as ApiPublicTestarEmailRouteImport } from './routes/api/public/testar-email'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AprovarTokenRoute = AprovarTokenRouteImport.update({
  id: '/aprovar/$token',
  path: '/aprovar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCampanhasCampanhaIdRoute =
  AuthenticatedCampanhasCampanhaIdRouteImport.update({
    id: '/campanhas/$campanhaId',
    path: '/campanhas/$campanhaId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPecasIndexRoute = AuthenticatedPecasIndexRouteImport.update({
  id: '/pecas/',
  path: '/pecas/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPecasPecaIdRoute =
  AuthenticatedPecasPecaIdRouteImport.update({
    id: '/pecas/$pecaId',
    path: '/pecas/$pecaId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicNotificacaoEmailRoute =
  ApiPublicNotificacaoEmailRouteImport.update({
    id: '/api/public/notificacao-email',
    path: '/api/public/notificacao-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTestarEmailRoute = ApiPublicTestarEmailRouteImport.update({
  id: '/api/public/testar-email',
  path: '/api/public/testar-email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/aprovar/$token': typeof AprovarTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/campanhas/$campanhaId': typeof AuthenticatedCampanhasCampanhaIdRoute
  '/pecas/$pecaId': typeof AuthenticatedPecasPecaIdRoute
  '/api/public/notificacao-email': typeof ApiPublicNotificacaoEmailRoute
  '/api/public/testar-email': typeof ApiPublicTestarEmailRoute
  '/pecas/': typeof AuthenticatedPecasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/aprovar/$token': typeof AprovarTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/campanhas/$campanhaId': typeof AuthenticatedCampanhasCampanhaIdRoute
  '/pecas/$pecaId': typeof AuthenticatedPecasPecaIdRoute
  '/api/public/notificacao-email': typeof ApiPublicNotificacaoEmailRoute
  '/api/public/testar-email': typeof ApiPublicTestarEmailRoute
  '/pecas': typeof AuthenticatedPecasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/aprovar/$token': typeof AprovarTokenRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/campanhas/$campanhaId': typeof AuthenticatedCampanhasCampanhaIdRoute
  '/_authenticated/pecas/$pecaId': typeof AuthenticatedPecasPecaIdRoute
  '/api/public/notificacao-email': typeof ApiPublicNotificacaoEmailRoute
  '/api/public/testar-email': typeof ApiPublicTestarEmailRoute
  '/_authenticated/pecas/': typeof AuthenticatedPecasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/redefinir-senha'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/painel'
    | '/aprovar/$token'
    | '/.lovable/oauth/consent'
    | '/campanhas/$campanhaId'
    | '/pecas/$pecaId'
    | '/api/public/notificacao-email'
    | '/api/public/testar-email'
    | '/pecas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/redefinir-senha'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/painel'
    | '/aprovar/$token'
    | '/.lovable/oauth/consent'
    | '/campanhas/$campanhaId'
    | '/pecas/$pecaId'
    | '/api/public/notificacao-email'
    | '/api/public/testar-email'
    | '/pecas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/redefinir-senha'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/painel'
    | '/aprovar/$token'
    | '/.lovable/oauth/consent'
    | '/_authenticated/campanhas/$campanhaId'
    | '/_authenticated/pecas/$pecaId'
    | '/api/public/notificacao-email'
    | '/api/public/testar-email'
    | '/_authenticated/pecas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AprovarTokenRoute: typeof AprovarTokenRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicNotificacaoEmailRoute: typeof ApiPublicNotificacaoEmailRoute
  ApiPublicTestarEmailRoute: typeof ApiPublicTestarEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/aprovar/$token': {
      id: '/aprovar/$token'
      path: '/aprovar/$token'
      fullPath: '/aprovar/$token'
      preLoaderRoute: typeof AprovarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/campanhas/$campanhaId': {
      id: '/_authenticated/campanhas/$campanhaId'
      path: '/campanhas/$campanhaId'
      fullPath: '/campanhas/$campanhaId'
      preLoaderRoute: typeof AuthenticatedCampanhasCampanhaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pecas/': {
      id: '/_authenticated/pecas/'
      path: '/pecas'
      fullPath: '/pecas/'
      preLoaderRoute: typeof AuthenticatedPecasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pecas/$pecaId': {
      id: '/_authenticated/pecas/$pecaId'
      path: '/pecas/$pecaId'
      fullPath: '/pecas/$pecaId'
      preLoaderRoute: typeof AuthenticatedPecasPecaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/notificacao-email': {
      id: '/api/public/notificacao-email'
      path: '/api/public/notificacao-email'
      fullPath: '/api/public/notificacao-email'
      preLoaderRoute: typeof ApiPublicNotificacaoEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/testar-email': {
      id: '/api/public/testar-email'
      path: '/api/public/testar-email'
      fullPath: '/api/public/testar-email'
      preLoaderRoute: typeof ApiPublicTestarEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedCampanhasCampanhaIdRoute: typeof AuthenticatedCampanhasCampanhaIdRoute
  AuthenticatedPecasPecaIdRoute: typeof AuthenticatedPecasPecaIdRoute
  AuthenticatedPecasIndexRoute: typeof AuthenticatedPecasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedCampanhasCampanhaIdRoute: AuthenticatedCampanhasCampanhaIdRoute,
  AuthenticatedPecasPecaIdRoute: AuthenticatedPecasPecaIdRoute,
  AuthenticatedPecasIndexRoute: AuthenticatedPecasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AprovarTokenRoute: AprovarTokenRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicNotificacaoEmailRoute: ApiPublicNotificacaoEmailRoute,
  ApiPublicTestarEmailRoute: ApiPublicTestarEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
